# Generated by Django 5.1.1 on 2024-09-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Framework o tecnología"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        max_length=10,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="skills/", verbose_name="Logotipo"),
                ),
            ],
            options={
                "verbose_name": "Frameworks",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Idioma")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            (1, "Elemental"),
                            (2, "Intermedio"),
                            (3, "Avanzado"),
                            (4, "Nativo"),
                        ],
                        max_length=10,
                        verbose_name="Nivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidades",
            },
        ),
        migrations.CreateModel(
            name="Program_language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Lenguaje")),
                (
                    "level",
                    models.CharField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        max_length=10,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="skills/", verbose_name="Logotipo"),
                ),
                ("primary_language", models.BooleanField(default=False)),
                ("other_languages", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Lenguajes de programación",
            },
        ),
        migrations.RemoveField(
            model_name="cv",
            name="skills",
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Formación",
                "verbose_name_plural": "Formaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Formación",
                "verbose_name_plural": "Formaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencias",
            },
        ),
        migrations.AddField(
            model_name="cv",
            name="frameworks",
            field=models.ManyToManyField(
                to="cv_generator.framework", verbose_name="Frameworks"
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="languages",
            field=models.ManyToManyField(
                to="cv_generator.language", verbose_name="Idiomas"
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv_generator.program_language",
                verbose_name="Basado en",
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="program_languages",
            field=models.ManyToManyField(
                to="cv_generator.program_language",
                verbose_name="Lenguajes de programación",
            ),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
