# Generated by Django 5.1.1 on 2024-09-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cv_generator",
            "0002_framework_language_program_language_remove_cv_skills_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_data",
            name="phone",
            field=models.IntegerField(verbose_name="Número de teléfono"),
        ),
        migrations.AlterField(
            model_name="contact_data",
            name="postal_code",
            field=models.IntegerField(verbose_name="Código Postal"),
        ),
    ]
