# Generated by Django 5.1.1 on 2024-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0003_alter_contact_data_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="actually_job",
            field=models.BooleanField(default=False, verbose_name="Trabajo actual"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(default=False, verbose_name="Fecha fin"),
        ),
    ]
