# Generated by Django 5.1.1 on 2024-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0004_alter_experience_actually_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framework",
            name="level",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=10,
                verbose_name="Nivel",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.CharField(
                choices=[
                    ("elemental", "Elemental"),
                    ("intermedio", "Intermedio"),
                    ("avanzado", "Avanzado"),
                    ("nativo", "Nativo"),
                ],
                max_length=10,
                verbose_name="Nivel",
            ),
        ),
        migrations.AlterField(
            model_name="program_language",
            name="level",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=10,
                verbose_name="Nivel",
            ),
        ),
    ]
