# Generated by Django 5.1.1 on 2024-09-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0005_alter_framework_level_alter_language_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certification",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Certificación",
                "verbose_name_plural": "Certificaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["-end_date"],
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencias",
            },
        ),
        migrations.AlterModelOptions(
            name="other_url",
            options={
                "verbose_name": "Otra url",
                "verbose_name_plural": "Otras urls de interés",
            },
        ),
    ]
