# Generated by Django 5.1.1 on 2024-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0007_cv_photo_alter_experience_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="range",
            field=models.CharField(
                default="Desarrollador Fullstack Django/React",
                max_length=300,
                verbose_name="Cargo",
            ),
            preserve_default=False,
        ),
    ]
